// Enter your actual selling prices here before publishing.
// Example: "baby-electric-nail-trimmer": 249
const PRICES = {
  "baby-electric-nail-trimmer": null,
  "baby-grooming-kit": null,
  "formula-snack-container": null,
  "baby-toddler-footwear": null,
  "newborn-gift-set": null,
  "baby-nest-lounger": null,
  "knitted-newborn-set": null,
  "double-stroller": null,
  "single-stroller-canopy": null,
  "single-stroller-full-canopy": null,
  "baby-bath-care-set": null,
  "baby-bouncer-seat": null,
  "bottle-warmer": null,
  "foldable-baby-bath": null,
  "children-gift-baskets": null,
  "compact-travel-stroller": null,
  "video-baby-monitor": null,
  "baby-fruit-feeder": null,
  "baby-play-gym": null,
  "bunny-comforter": null,
  "muslin-swaddle": null,
  "hooded-baby-towel": null,
  "baby-floor-seat": null,
  "adjustable-bath-seat": null,
  "wooden-cot-mobile": null,
  "toddler-potty": null,
  "wooden-nursery-mobile": null,
  "kidilo-g308": null,
};
